[package]
name = "achat"
version = "0.1.0"
edition = "2021"
description = "Super simple tokio chat server for educational purposes."
repository = "https://github.com/barafael/achat"
license = "Apache-2.0"
default-run = "chat"

[[bin]]
name = "chat"
path = "bin/chat.rs"

[[bin]]
name = "dump_client"
path = "bin/dump_client.rs"

[[bin]]
name = "echo"
path = "bin/echo.rs"

[[bin]]
name = "collector"
path = "bin/collector.rs"

[[bin]]
name = "chat_with_announce"
path = "bin/chat_with_announce.rs"

[[bin]]
name = "chat_with_cancel"
path = "bin/chat_with_cancel.rs"

[[bin]]
name = "dump_gui"
path = "bin/dump_client_gui.rs"

[dev-dependencies]
tokio-test = "0.4.2"

[dependencies]
anyhow = "1.0.57"
clap = { version = "3.1.18", features = ["derive"] }
console-subscriber = "0.1.5"
futures = "0.3.21"
klask = { git = "https://github.com/barafael/klask" }
serde_json = "1.0.81"
tokio = { version = "1.18.2", features = [
    "io-util",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "sync",
    "time",
    "tracing",
] }
tokio-util = "0.7.1"
