name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check-test:
    name: Format + check + test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: default
          toolchain: nightly
          override: true
      - name: Install packages (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libgtk-3-dev # libgtk-3-dev is used by rfd
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@v2
      - name: Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - name: Check all features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features
      - name: Check default features
        uses: actions-rs/cargo@v1
        with:
          command: check
      - name: Check no default features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --no-default-features --lib
      - name: Test doc-tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
      - name: cargo doc --lib
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --lib --no-deps --all-features
      - name: cargo doc --document-private-items
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --document-private-items --no-deps --all-features
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
#      - name: Build Binaries
#        uses: actions-rs/cargo@v1
#        with:
#          command: build --bins
#          args: --all-features
#      - name: Build Examples
#        uses: actions-rs/cargo@v1
#        with:
#          command: build --examples
#          args: --all-features
